import { expect, test, type Page } from "@playwright/test";

const configuredBasePath = process.env.PUBLIC_BASE_PATH?.trim() || "/";
const basePath = configuredBasePath === "/" ? "" : `/${configuredBasePath.replace(/^\/+|\/+$/g, "")}`;
const appPath = (pathname: string) => `${basePath}${pathname}` || "/";
const paipanRef = `pp_${"m".repeat(32)}`;
const expiresAt = "2030-01-01T00:00:00.000Z";
const usage = { recommendationPercent: 95, culturePercent: 94, genderTendency: 3, usageCount: 1000, firstCharacterPercent: 84, malePercent: 47, femalePercent: 53, sourceNote: "来源站统计，仅作参考" };
const reading = (number: number, rating: string) => ({ number, yinYang: number % 2 ? "阳" : "阴", rating, summary: "福寿圆满，富贵荣誉。", categories: "吉祥运", foundation: "木星", family: "家门余庆", health: "健康", meaning: "含义详解", detail: "完整数理正文" });
const character = (input: string, traditional: string, strokes: number, element: string) => ({ input, simplified: input, traditional, pinyin: "chén", radical: "辰", kangxiStrokes: strokes, calculationStrokes: strokes, element, rating: "吉", common: true, nameUsageClass: "姓名学", nameExplanation: "星辰。", namingMeaning: "指时日星月。", namingImplication: "寓意吉祥。", taboos: "避免同韵。", usageReference: usage });
const grid = (key: string, label: string, number: number, element: string, rating: string) => ({ key, label, number, interpretationNumber: ((number - 1) % 81) + 1, element, rating, interpretation: reading(((number - 1) % 81) + 1, rating) });
const threeTalents = (title: string) => ({ title, rating: "吉", summary: "易达目的，轻易成功。", foundationLuck: "基础安定", foundationRating: "吉", successLuck: "成功顺利", successRating: "吉", relationships: "人际圆融", relationshipsRating: "吉", personality: "性情稳健", liugeSummary: null, liugeRating: null });
const scoreBreakdown = (total: number) => ({ components: [{ key: "heaven", label: "天格", weightPercent: 20, rawScore: 70, contribution: 14 }, { key: "earth", label: "地格", weightPercent: 20, rawScore: 70, contribution: 14 }, { key: "person", label: "人格", weightPercent: 20, rawScore: 90, contribution: 18 }, { key: "threeTalents", label: "三才", weightPercent: 40, rawScore: 55, contribution: 22 }], total, note: "仅作传统姓名学参考" });
const common = { dataset: { status: "official", version: "xingming-20260814.r1", dictionaryVersion: "kangxi-cn-20260813.r3", numerologyVersion: "yp-20260813.r1" }, elementRelations: [{ from: "天格", to: "人格", relation: "相生", summary: "天格 → 人格：相生" }, { from: "人格", to: "地格", relation: "相克", summary: "人格 → 地格：相克" }] };
const wugeChart = { ...common, school: "wuge", name: { surname: "李", givenName: "明", fullName: "李明" }, characters: [character("李", "李", 7, "火"), character("明", "明", 8, "水")], grids: [grid("heaven", "天格", 8, "金", "吉"), grid("person", "人格", 15, "土", "大吉"), grid("earth", "地格", 9, "水", "凶"), grid("outer", "外格", 2, "木", "凶"), grid("total", "总格", 15, "土", "大吉")], threeTalents: threeTalents("金土水"), score: 68, scoreBreakdown: scoreBreakdown(68), totalGridDescription: reading(15, "大吉") };
const liugeChart = { ...common, school: "liuge", name: { surname: "歐陽", givenName: "子涵", fullName: "歐陽子涵" }, characters: [character("欧", "歐", 15, "土"), character("阳", "陽", 17, "土"), character("子", "子", 3, "水"), character("涵", "涵", 12, "水")], grids: [grid("heaven", "天格", 32, "木", "吉"), grid("person", "人格", 20, "水", "凶"), grid("earth", "地格", 15, "土", "吉"), grid("outer", "外格", 27, "金", "半吉半凶"), grid("total", "总格", 47, "金", "吉"), grid("change", "变格", 29, "水", "半吉半凶")], threeTalents: { ...threeTalents("木水土"), rating: "【凶多于吉】" }, score: 56, scoreBreakdown: scoreBreakdown(56), totalGridDescription: reading(47, "吉") };

async function expectNoOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); }
async function mockXingming(page: Page) {
  let latestRequest = { surname: "李", givenName: "明", school: "wuge" };
  let latestChart: typeof wugeChart | typeof liugeChart = wugeChart;
  await page.route("**/api/v1/paipan/xingming/chart", async (route) => { latestRequest = route.request().postDataJSON(); latestChart = latestRequest.school === "liuge" ? liugeChart : wugeChart; await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ...latestChart, paipan_ref: paipanRef, expiresAt }) }); });
  await page.route("**/api/v1/paipan/xingming/context", async (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ schemaVersion: "guoxue.paipan.xingming.v2", chartType: "xingming", paipan_ref: paipanRef, generatedAt: "2026-08-14T03:00:00.000Z", expiresAt, chartRequest: latestRequest, chart: latestChart }) }));
  return () => latestRequest;
}

for (const viewport of [{ width: 360, height: 800 }, { width: 390, height: 844 }, { width: 430, height: 932 }]) {
  test(`five-grid flow restores without overflow at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport); const request = await mockXingming(page); await page.goto(appPath("/paipan"));
    await expect(page.getByRole("link", { name: /姓名学/ })).toBeVisible(); await page.getByRole("link", { name: /姓名学/ }).click();
    await expect(page.getByText(/正式康熙字库/)).toHaveCount(0); const fullNameInput = page.getByRole("textbox", { name: "姓名", exact: true }); expect(await fullNameInput.getAttribute("maxlength")).toBeNull(); await fullNameInput.dispatchEvent("compositionstart"); await fullNameInput.fill("liming"); await expect(fullNameInput).toHaveValue("liming"); await fullNameInput.fill("李明"); await fullNameInput.dispatchEvent("compositionend", { data: "李明" }); await page.getByRole("button", { name: "开始排盘" }).click();
    expect(request()).toEqual({ surname: "李", givenName: "明", school: "wuge" }); await expect(page.getByRole("heading", { name: "李明" })).toBeVisible(); await expect(page.getByLabel("姓氏 李").getByRole("article")).toHaveCount(1); await expect(page.getByLabel("名字 明").getByRole("article")).toHaveCount(1); await expect(page.getByLabel("名字用字 明").getByText("康熙笔画")).toBeVisible(); await expect(page.getByLabel("名字用字 明").getByLabel("五行 水")).toBeVisible(); await expect(page.getByLabel("五格关系图")).toBeVisible(); await expect(page.getByLabel("五格关系图").getByLabel(/^五行 /)).toHaveCount(5); await expect(page.getByLabel("三才五行 金土水").getByLabel(/^五行 /)).toHaveCount(3); await expect(page.locator("[data-xingming-grid]")).toHaveCount(5); await expect(page.locator(".xingming-grids-card details[open]")).toHaveCount(5); await expect(page.getByText("数理摘要")).toHaveCount(0); await expect(page.getByText("传统分类")).toHaveCount(0); await expect(page.getByText(/天格由姓氏笔画计算/)).toBeVisible(); await expect(page.getByText(/同为 15 数/)).toBeVisible(); await expect(page.getByText(/男性双妻运|刚情运|常见说法/)).toHaveCount(0); await expect(page.getByText("评分构成")).toHaveCount(0); await expectNoOverflow(page);
    await page.reload(); await expect(page.getByRole("heading", { name: "李明" })).toBeVisible(); await expectNoOverflow(page);
  });
}

test("six-grid splits a compound surname and exposes manual adjustment", async ({ page }) => {
  const request = await mockXingming(page); await page.goto(appPath("/paipan/xingming")); await page.getByRole("button", { name: /三才六格/ }).click(); await page.getByRole("textbox", { name: "姓名", exact: true }).fill("欧阳子涵"); await page.getByRole("button", { name: "开始排盘" }).click();
  expect(request()).toEqual({ surname: "欧阳", givenName: "子涵", school: "liuge" }); await expect(page.getByRole("heading", { name: "歐陽子涵" })).toBeVisible(); await expect(page.getByLabel("姓氏 歐陽").getByRole("article")).toHaveCount(2); await expect(page.getByLabel("名字 子涵").getByRole("article")).toHaveCount(2); const normalizedCharacter = page.getByLabel("姓氏用字 陽"); await expect(normalizedCharacter.getByText("阳", { exact: true })).toBeVisible(); await expect(normalizedCharacter.getByText("陽", { exact: true })).toHaveCount(2); await expect(page.getByLabel("六格关系图")).toBeVisible(); await expect(page.locator("[data-xingming-grid]")).toHaveCount(6); await expect(page.locator(".xingming-grids-card details[open]")).toHaveCount(6); const adjustButton = page.getByRole("button", { name: "调整姓名" }); await expect(adjustButton).toHaveAttribute("data-paipan-action", "edit"); await expect(adjustButton).toHaveClass(/paipan-action-button--edit/); await adjustButton.click(); const editor = page.locator(".xingming-name-editor"); await expect(editor.getByLabel("姓氏")).toHaveValue("欧阳"); await expect(editor.getByLabel("名字")).toHaveValue("子涵"); await expect(editor.getByText(/可手动调整姓氏和名字/)).toBeVisible(); await editor.getByLabel("姓氏").fill("司马"); await editor.getByLabel("名字").fill("光"); await editor.getByRole("button", { name: "重新排盘" }).click(); expect(request()).toEqual({ surname: "司马", givenName: "光", school: "liuge" }); await expect(editor).toHaveCount(0); await expectNoOverflow(page);
});
