CREATE TABLE chinese_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jtz VARCHAR(255),
    zi VARCHAR(255) NOT NULL,
    py VARCHAR(255),
    wubi VARCHAR(255),
    bushou VARCHAR(255),
    bihua INTEGER NOT NULL,
    pinyin VARCHAR(255),
    jijie CLOB,
    xiangjie CLOB,
    wx VARCHAR(255),
    jx VARCHAR(255),
    kx_bihua VARCHAR(100) NOT NULL DEFAULT '',
    CONSTRAINT uq_chinese_dictionary_zi UNIQUE (zi)
);

CREATE TABLE chinese_dictionary_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias VARCHAR(255) NOT NULL,
    target_zi VARCHAR(255) NOT NULL,
    relation_type VARCHAR(50) NOT NULL,
    source_version VARCHAR(255) NOT NULL,
    CONSTRAINT uq_chinese_dictionary_alias UNIQUE (alias),
    CONSTRAINT fk_chinese_dictionary_alias_target FOREIGN KEY (target_zi) REFERENCES chinese_dictionary (zi)
);

CREATE TABLE chinese_dictionary_profile (
    zi VARCHAR(255) PRIMARY KEY,
    recommendation_percent INTEGER,
    culture_percent INTEGER,
    gender_tendency INTEGER,
    common_flag INTEGER,
    name_usage_class VARCHAR(255),
    name_explanation CLOB,
    naming_meaning CLOB,
    naming_implication CLOB,
    usage_count BIGINT,
    first_character_percent INTEGER,
    male_percent INTEGER,
    female_percent INTEGER,
    taboos_text CLOB,
    source_version VARCHAR(255) NOT NULL,
    CONSTRAINT fk_chinese_dictionary_profile_target FOREIGN KEY (zi) REFERENCES chinese_dictionary (zi),
    CONSTRAINT ck_chinese_dictionary_profile_recommendation CHECK (recommendation_percent IS NULL OR recommendation_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_chinese_dictionary_profile_culture CHECK (culture_percent IS NULL OR culture_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_chinese_dictionary_profile_gender CHECK (gender_tendency IS NULL OR gender_tendency BETWEEN 0 AND 9),
    CONSTRAINT ck_chinese_dictionary_profile_common CHECK (common_flag IS NULL OR common_flag IN (0, 1))
);

CREATE TABLE yp_81 (
    num INTEGER NOT NULL,
    yy VARCHAR(255),
    jx VARCHAR(255),
    als VARCHAR(255),
    content CLOB,
    CONSTRAINT uq_yp_81_num UNIQUE (num),
    CONSTRAINT ck_yp_81_num_range CHECK (num BETWEEN 1 AND 81)
);

CREATE TABLE yp_sancai (
    title VARCHAR(50) NOT NULL,
    yy VARCHAR(255),
    jx VARCHAR(255),
    content VARCHAR(2000),
    jcy VARCHAR(255),
    jx1 VARCHAR(255),
    cgy VARCHAR(255),
    jx2 VARCHAR(255),
    rjgx VARCHAR(255),
    jx3 VARCHAR(255),
    xg VARCHAR(255),
    sancai_liu_result VARCHAR(2000),
    sancai_liu_jx VARCHAR(255),
    CONSTRAINT uq_yp_sancai_title UNIQUE (title),
    CONSTRAINT ck_yp_sancai_title_length CHECK (CHAR_LENGTH(title) = 3),
    CONSTRAINT ck_yp_sancai_title_elements CHECK (
        SUBSTRING(title, 1, 1) IN ('金', '木', '水', '火', '土') AND
        SUBSTRING(title, 2, 1) IN ('金', '木', '水', '火', '土') AND
        SUBSTRING(title, 3, 1) IN ('金', '木', '水', '火', '土')
    )
);
